version: "3.5"
services:
  web-service:
    restart: always
    privileged: true
    tty: true
    volumes:
      - ./chat-app-backend/web-service:/home/ubuntu/service
    image: namlestudy/web-service:dev
    ports:
      - "6001:1337"
    environment:
      - DATABASE_URL=mysql://root:root@database:3306/chat_app
      - NODE_ENV=dev
      - MODE=DEV
      - RABBIT_MQ_ADDR=rabbitmq-service:5672
      - MYSQL_HOST=database
      - MYSQL_ROOT_PASSWORD=root
      - USER_MAPPING_ADDR=user-mapping-service:6380
      - REDIS_SESSION_ADDR=session-service:6382
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:1337/health 2>&1 | grep healthy"]
      interval: 30s
      timeout: 5s
      retries: 5
    container_name: backend-web-service-dev
    depends_on:
      - database
      - session-service
    networks:
      - chat-network
  chat-service:
    privileged: true
    restart: always
    tty: true
    volumes:
      - ./chat-app-backend/chat-service:/home/ubuntu/service
    image: namlestudy/chat-service:dev
    ports:
      - "6002:1337"
    environment:
      - NODE_ENV=dev
      - MODE=DEV
      - RABBIT_MQ_ADDR=rabbitmq-service:5672
      - MYSQL_HOST=database
      - MYSQL_ROOT_PASSWORD=root
      - USER_MAPPING_ADDR=user-mapping-service:6380
      - REDIS_SESSION_ADDR=session-service:6382
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f localhost:1337/health 2>&1 | grep healthy"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 5
    container_name: backend-chat-service-dev
    networks:
      - chat-network
    depends_on:
      - database
      - user-mapping-service
      - session-service
      - rabbitmq-service
  database:
    volumes:
      - "./data/mysql:/var/lib/mysql"
    command: "--default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    image: mysql:8
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=chat_app"
    ports:
      - "33069:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin" ,"ping", "-h", "localhost", '-u', 'root', "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 20s
      retries: 10
    networks:
      - chat-network
    container_name: mysql-chat-app
  user-mapping-service:
    privileged: false
    image: redis:6.2
    entrypoint: ["redis-server"]
    command: ["--appendonly", "no", "--save", "900", "10", "--maxmemory", "1gb", "--maxmemory-policy", "allkeys-lru", "--port", "6380"]
    ports:
     - "6380:6380"
    volumes:
     - ./database/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    container_name: user-mapping-service
    networks:
      - chat-network
  session-service:
    privileged: false
    image: redis:6.2
    entrypoint: ["redis-server"]
    command: ["--appendonly", "no", "--save", "900", "10", "--maxmemory", "1gb", "--maxmemory-policy", "allkeys-lru", "--port", "6382"]
    ports:
     - "6382:6382"
    volumes:
     - ./database/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6382", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    container_name: session-service
    networks:
      - chat-network
  rabbitmq-service:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 5673:5672
      - 15673:15672
    container_name: rabbitmq-service
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
